PLAGAS = [
    "Archips xylosteana",
    "Cerura iberica",
    "Chrysomela populi",
    "Cossus cossus",
    "Crepidodera spp",
    "Cryptorhynchus lapathi",
    "Cytospora chrysosperma",
    "Dothichiza populea",
    "Gypsonoma aceriana",
    "Laothoe populi",
    "Lepidosaphes ulmi",
    "Leucoma salicis",
    "Lonsdalea quercina subsp populi",
    "Marssonina brunnea",
    "Melampsora spp",
    "Melanophila picta",
    "Paranthrene tabaniformis",
    "Pemphigus spp",
    "Phloemyzus passerinii",
    "Phratora laticolis",
    "SANO",
    "Saperda carcharias",
    "Saperda populnea",
    "Sesia apiformis",
    "Taphrina populnea (Taphrina aurea)",
    "Trypophloeus spp",
    "Venturia populina",
    "Xanthomonas populi",
]
